repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2        # oder aktuelle Version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4        # oder aktuelle Version
    hooks:
      - id: ruff
        args: ["--fix"] 

